# Site settings
title: Daniel Bolger
email: daniel@bolger.com.au
description: > # this means to ignore newlines until "baseurl:"
  I am a software developer based in Melbourne, Australia. I am passionate
  about writing maintainable code. I am deeply interested in processes, methods
  and tooling that enables me to delivery software efficiently.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://daniel.bolger.id.au" # the base hostname & protocol for your site
twitter_username: dtbolger
github_username:  bolger

# Build settings
markdown: kramdown
